#!/bin/bash
#
# Merge the develop branch to the master branch iff develop passes
#
#

# Remote branches
branches=$(git branch -r | egrep -v "HEAD" | sed 's/origin\///g')

passing_branches=$(travis branches | egrep passed | egrep "develop:" | cut -f 1 -d ":")

for branch in $passing_branches
do
  git checkout $branch
  git pull
  git checkout master
  git merge $branch
  git push
  git checkout develop
done


