#!/bin/bash

for folder in $(ls -d */)
do

  cd $folder

  if [ -d ".git" ]
  then
    echo "git folder: "$folder
    git add --all :/
    git commit -m "Shortened to 'get_sim_twal_same_n_muts_fun', thanks @lintr-bot"
    git pull
    git push
  fi

  cd ..
done
