#!/bin/bash
#
# For all folders, merge all passing branches to the richel branch
#
# Usage:
#
# ./git/recursive_merge_all_passing_to_richel
#

for folder in $(ls -d */)
do
  cd folder
  ../git/merge_all_passing_to_richel
  cd ..
done


